language: node_js
node_js:
  - node

node_js:
  - 8 # use LTS version, newest version 10 crashes

branches:
  only:
    - master

after_success:
  # Tests don't put the script together, do that now
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: target
